LOCAL_C_INCLUDES := \
  $(LIBS_SOX_PATH)/SoX \
  $(LIBS_SOX_PATH)/sox-code/libgsm \
  $(LIBS_SOX_PATH)/sox-code/src \
  $(LIBS_SOX_PATH)/sox-code/src/fmemopen-ios \
  $(LIBS_SOX_PATH)/sox-code/src/bit-rot \
  $(LIBS_SOX_PATH)/sox-code/src/bit-rot/CoreAudio \
  $(LIBS_SOX_PATH)/sox-code/src/bit-rot/sys
  
LOCAL_CFLAGS += -DHAVE_CONFIG_H
LOCAL_CFLAGS += -DANDROID_NDK

LOCAL_PATH := $(LIBS_SOX_PATH)/sox-code
LOCAL_MODULE := sox

LOCAL_SRC_FILES := \
  libgsm/add.c     \
  libgsm/code.c \
  libgsm/decode.c \
  libgsm/gsm_create.c \
  libgsm/gsm_decode.c \
  libgsm/gsm_destroy.c \
  libgsm/gsm_encode.c \
  libgsm/gsm_option.c \
  libgsm/long_term.c \
  libgsm/lpc.c \
  libgsm/preprocess.c \
  libgsm/rpe.c \
  libgsm/short_term.c \
  libgsm/table.c \
  src/8svx.c \
  src/adpcm.c \
  src/adpcms.c \
  src/aifc-fmt.c \
  src/aiff-fmt.c \
  src/aiff.c \
  src/al-fmt.c \
  src/amr-nb.c \
  src/amr-wb.c \
  src/au.c \
  src/avr.c \
  src/bend.c \
  src/biquad.c \
  src/biquads.c \
  src/caf.c \
  src/cdr.c \
  src/chorus.c \
  src/compand.c \
  src/compandt.c \
  src/contrast.c \
  src/cvsd-fmt.c \
  src/cvsd.c \
  src/dat.c \
  src/dcshift.c \
  src/delay.c \
  src/dft_filter.c \
  src/dither.c \
  src/divide.c \
  src/downsample.c \
  src/dvms-fmt.c \
  src/earwax.c \
  src/echo.c \
  src/echos.c \
  src/effects.c \
  src/effects_i.c \
  src/effects_i_dsp.c \
  src/f4-fmt.c \
  src/f8-fmt.c \
  src/fade.c \
  src/fap.c \
  src/fft4g.c \
  src/fir.c \
  src/firfit.c \
  src/flanger.c \
  src/fmemopen-ios/fmemopen.c \
  src/fmemopen-ios/open_memstream.c \
  src/formats.c \
  src/formats_i.c \
  src/g711.c \
  src/g721.c \
  src/g723_24.c \
  src/g723_40.c \
  src/g72x.c \
  src/gain.c \
  src/getopt.c \
  src/gsm.c \
  src/gsrt.c \
  src/hcom.c \
  src/hilbert.c \
  src/htk.c \
  src/ima-fmt.c \
  src/ima_rw.c \
  src/input.c \
  src/la-fmt.c \
  src/ladspa.c \
  src/libsox.c \
  src/libsox_i.c \
  src/loudness.c \
  src/lu-fmt.c \
  src/mat4.c \
  src/mat5.c \
  src/maud.c \
  src/mcompand.c \
  src/mp3.c \
  src/noiseprof.c \
  src/noisered.c \
  src/nulfile.c \
  src/output.c \
  src/overdrive.c \
  src/pad.c \
  src/paf.c \
  src/phaser.c \
  src/prc.c \
  src/pvf.c \
  src/rate.c \
  src/raw-fmt.c \
  src/raw.c \
  src/remix.c \
  src/repeat.c \
  src/reverb.c \
  src/reverse.c \
  src/s1-fmt.c \
  src/s2-fmt.c \
  src/s3-fmt.c \
  src/s4-fmt.c \
  src/sd2.c \
  src/sf.c \
  src/silence.c \
  src/sinc.c \
  src/skeleff.c \
  src/skelform.c \
  src/smp.c \
  src/sndfile.c \
  src/sounder.c \
  src/soundtool.c \
  src/sox-fmt.c \
  src/speed.c \
  src/speexdsp.c \
  src/sphere.c \
  src/splice.c \
  src/stat.c \
  src/stats.c \
  src/stretch.c \
  src/swap.c \
  src/synth.c \
  src/tempo.c \
  src/tremolo.c \
  src/trim.c \
  src/tx16w.c \
  src/u1-fmt.c \
  src/u2-fmt.c \
  src/u3-fmt.c \
  src/u4-fmt.c \
  src/ul-fmt.c \
  src/upsample.c \
  src/util.c \
  src/vad.c \
  src/voc.c \
  src/vol.c \
  src/vox-fmt.c \
  src/vox.c \
  src/w64.c \
  src/wav.c \
  src/wavpack.c \
  src/wve.c \
  src/xa.c \
  src/xi.c \
  src/xmalloc.c

